# Generated by Django 2.1.4 on 2020-06-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='posted_by',
            new_name='created_by',
        ),
    ]
